#!/bin/sh
#

#
# Copyright (C) 2009-2021 Marcello Balduccini. All Rights Reserved.
#
# Convert an ASCII file to a C-style string.
#

echo "/* file automatically generated by fileToC.sh from $1 */"

# The use of "\" at the end of a line to continue a string on the
# next line seems to be incompatible with certain versions of gcc.
# For better compatibility, we open and close the quotes on each line.
#echo "\"\\"
#sed -e "s/\"/\\\"/g"  -e 's/\\/\\\\/g' -e 's/^\(.*\)$/\1\\n\\/' $1
#echo "\\n\""

sed -e "s/\"/\\\"/g"  -e 's/\\/\\\\/g' -e 's/^\(.*\)$/"\1\\n"/' $1
