#ifndef EZCSP_SOLVER_TYPES_H
#define EZCSP_SOLVER_TYPES_H

#define CPSOLVER_SICSTUS4	0
#define CPSOLVER_SICSTUS3	1
#define CPSOLVER_BPROLOG	2
#define CPSOLVER_SWIPROLOG	3
#define CPSOLVER_GAMS		4
#define CPSOLVER_MINIZINC	5
#define CPSOLVER_GUROBI		6

#endif /* EZCSP_SOLVER_TYPES_H */
