(set-info :smt-lib-version 2.6)
(set-option :produce-models true)
(set-option :produce-assignments true)
(set-logic QF_LIA)
(declare-const |a| Bool)
(declare-const x Int)
(assert (ite |a| (> (+ 0 x) 5) true))
(assert (not (> (+ 0 x) (- 1))))
(check-sat)
(get-value (x |a|))
